services:
  xilinxbuild:
    #user: root
    build:
      context: ./xilinx-installer
      dockerfile: Dockerfile
    volumes:
      - .:/home/petalinux/project
      - ./outputdir-garud:/home/petalinux/outdir
    command: su petalinux bash -c "ls /home/petalinux/ && \
            git config --global --add safe.directory /home/petalinux/project && \
            git config --global --add safe.directory /home/petalinux/project/loki && \
            git config --global --add safe.directory /home/petalinux/project/garud-fw && \
            source /tools/Xilinx/Vivado/2023.2/settings64.sh && \
            source /tools/Xilinx/Vitis/2023.2/settings64.sh && \
            source /opt/xilinx/petalinux_install/2023.2/settings.sh && \
            export LD_PRELOAD=/lib/x86_64-linux-gnu/libudev.so.1 && \
            cd /home/petalinux/project && \
            yocto_tmpdir=/tmp/babyd XILINX_VIVADO=/tools/Xilinx/Vivado/2023.2 make"

    # This is potentially required to ensure that libraries relocate properly when using selinux on host
    #security_opt:
    #  - label=disable
    deploy:
      resources:
        limits:
          memory: 20G
