# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "lokitemplate"
BBFILE_PATTERN_lokitemplate = "^${LAYERDIR}/"
BBFILE_PRIORITY_lokitemplate = "9"
LAYERVERSION_lokitemplate = "1"
LAYERSERIES_COMPAT_lokitemplate = "langdale"

# Tell the layer to install template-instance (odin-control instance) by default.
IMAGE_INSTALL:append = " template-instance"
